### ISSUE TITLE
configure: error: wrong uv library version or library not found

### ISSUE THREAD

**Issue by twomiao** [amphp/ext-uv#105]
**PHP information:**
> PHP 7.4.16 (cli) (built: Apr 28 2021 18:20:46) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Error message:**
> checking for libuv... checking for uv_version in -luv... no 
> configure: error: wrong uv library version or library not found
> Lack of vu environment, how to solve it?

**Comment by iggyvolz** [comment]
You would have to install the UV package on your operating system - https://pkgs.org/search/?q=libuv

On Ubuntu/Debian I found success with `apt install libuv1`, it looks like Alpine uses `apk add libuv` and Fedora/CentOS/RHEL uses `yum install libuv`.

**Comment by kelunik** [comment]
You'll likely need `libuv1-dev` for the header files.
