### ISSUE TITLE
Closing resource before closing uv poll: infinite polling (100% CPU usage)

### ISSUE THREAD

**Issue by uasan** [amphp/ext-uv#40]
This not bug, but how to handle this event correctly?

```PHP
<?php

$loop   = uv_default_loop();
$server = stream_socket_server('tcp://0.0.0.0:8000');
$client = stream_socket_client('tcp://0.0.0.0:8000');

$pollServer = uv_poll_init($loop, $server);
$pollClient = uv_poll_init($loop, $client);

uv_poll_start($pollClient, 1, function($poll, $status, $events, $fd)
{
	static $i = 0;

	$buf = @stream_get_contents($fd, -1);

	if($buf === false)
	{
		uv_close($poll);
	}

	echo (++$i)."\r";
});

uv_poll_start($pollServer, 1, function() use($server)
{
	$client = stream_socket_accept($server);

	fclose($client);

	echo "SERVER: ACCEPT && CLOSE: CLIENT: $client\n";
});

uv_run($loop);
```
Is similar for the same reason
[https://github.com/amphp/amp/issues/112](https://github.com/amphp/amp/issues/112)

> The user should not close a file descriptor while it is being polled by an active poll handle. This can cause the handle to report an error, but it might also start polling another socket. However the fd can be safely closed immediately after a call to uv_poll_stop() or uv_close().

http://docs.libuv.org/en/v1.x/poll.html

**Comment by bwoebi** [comment]
Well, `$buf` always returns `""`, not false here.

If you check against `== ""`, then your script runs fine (it will stall inside uv_run() as the $pollServer poll is still active then).

**Comment by uasan** [comment]
Yes, but well this is a very simple example, I'll try to reproduce, As stated in the documentation - it might also start polling another socket.

**Comment by bwoebi** [comment]
Well, please try to reproduce, I'm pretty sure the error is not on the extension side here.
